In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/Student Social Media And Mental Health Impact.csv")

In [4]:
df.head()

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
0,21,Male,Other,Undergraduate,Facebook,Networking,4.0,134,4.5,2.2,6.7,Medium,6.8
1,23,Female,Other,Graduate,LinkedIn,Education,1.6,73,7.0,2.4,8.6,Low,7.6
2,22,Male,Canada,Undergraduate,Instagram,Entertainment,4.6,166,4.0,1.8,6.7,Medium,7.0
3,18,Male,Other,High School,Snapchat,Entertainment,7.0,220,1.0,1.7,5.4,Very High,5.3
4,24,Female,Other,Graduate,Facebook,Networking,7.5,237,1.0,1.1,5.0,Very High,4.4

In [5]:
df.shape

(5000, 13)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      5000 non-null   int64
 1   Gender                   5000 non-null   str
 2   Country                  5000 non-null   str
 3   Academic_Level           5000 non-null   str
 4   Most_Used_Platform       5000 non-null   str
 5   Purpose_Of_Use           5000 non-null   str
 6   Avg_Daily_Usage_Hours    5000 non-null   float64
 7   Daily_Unlocks            5000 non-null   int64
 8   Study_Hours              5000 non-null   float64
 9   Physical_Activity_Hours  5000 non-null   float64
 10  Sleep_Hours_Per_Night    5000 non-null   float64
 11  Stress_Level             5000 non-null   str
 12  Mental_Health_Score      5000 non-null   float64
dtypes: float64(5), int64(2), str(6)
memory usage: 507.9 KB

In [7]:
df.columns

Index(['Age', 'Gender', 'Country', 'Academic_Level', 'Most_Used_Platform',
       'Purpose_Of_Use', 'Avg_Daily_Usage_Hours', 'Daily_Unlocks',
       'Study_Hours', 'Physical_Activity_Hours', 'Sleep_Hours_Per_Night',
       'Stress_Level', 'Mental_Health_Score'],
      dtype='str')

In [8]:
df.describe()

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,20.82180,5.078460,171.452600,3.008420,1.751000,6.634580,6.230980
std,1.73662,1.653913,42.858254,1.637018,0.668398,1.221391,1.278701
min,18.00000,1.000000,62.000000,0.300000,-0.400000,3.600000,3.600000
25%,19.00000,3.800000,140.000000,1.500000,1.300000,5.600000,5.100000
50%,21.00000,5.000000,171.000000,2.800000,1.700000,6.600000,6.100000
75%,22.00000,6.300000,204.000000,4.200000,2.200000,7.500000,7.100000
max,24.00000,8.800000,273.000000,8.300000,4.100000,9.900000,9.400000

In [9]:
df.isnull().sum()

Age                        0
Gender                     0
Country                    0
Academic_Level             0
Most_Used_Platform         0
Purpose_Of_Use             0
Avg_Daily_Usage_Hours      0
Daily_Unlocks              0
Study_Hours                0
Physical_Activity_Hours    0
Sleep_Hours_Per_Night      0
Stress_Level               0
Mental_Health_Score        0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(2)

In [12]:
df.columns.tolist()

['Age',
 'Gender',
 'Country',
 'Academic_Level',
 'Most_Used_Platform',
 'Purpose_Of_Use',
 'Avg_Daily_Usage_Hours',
 'Daily_Unlocks',
 'Study_Hours',
 'Physical_Activity_Hours',
 'Sleep_Hours_Per_Night',
 'Stress_Level',
 'Mental_Health_Score']

In [13]:
df = df.drop_duplicates()

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df[df['Physical_Activity_Hours'] < 0]

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
2277,20,Male,Other,Undergraduate,Facebook,Networking,6.8,222,2.6,-0.1,4.7,Very High,4.6
2923,23,Female,USA,Graduate,Snapchat,Entertainment,7.9,223,1.1,-0.1,5.8,Very High,5.2
3056,19,Male,Other,Undergraduate,LinkedIn,Education,7.8,252,1.6,-0.3,5.7,Very High,4.3
3422,24,Male,Other,Graduate,Twitter,News,8.2,245,0.7,-0.1,5.8,Very High,4.4
3882,20,Female,Other,Undergraduate,YouTube,Education,5.5,207,2.2,-0.2,5.1,Very High,5.7
4058,21,Male,Other,Undergraduate,YouTube,Education,5.8,200,2.0,-0.1,7.4,High,6.2
4243,20,Female,Other,Undergraduate,YouTube,Education,5.6,207,2.6,-0.4,5.0,Very High,5.4
4406,20,Male,Other,Undergraduate,Facebook,Networking,7.2,222,2.6,-0.3,4.5,Very High,4.5
4522,19,Male,Other,Undergraduate,LinkedIn,Education,8.1,252,2.2,-0.2,5.7,Very High,4.1
4771,21,Male,India,Undergraduate,TikTok,Entertainment,7.6,222,1.0,-0.2,5.2,Very High,4.5

In [16]:
df = df.drop_duplicates()

In [17]:
df = df[df['Physical_Activity_Hours'] >= 0]

In [18]:
df.shape

(4988, 13)

In [19]:
df['Physical_Activity_Hours'].min()

np.float64(-0.0)

In [23]:
df['Gender'].value_counts()

Gender
Male      2627
Female    2361
Name: count, dtype: int64

In [24]:
df['Country'].value_counts()

Country
Other         1871
India          388
USA            353
Canada         230
Australia      198
              ...
Montenegro       1
Bosnia           1
Kuwait           1
Yemen            1
Syria            1
Name: count, Length: 111, dtype: int64

In [25]:
df['Academic_Level'].value_counts()

Academic_Level
Undergraduate    3622
Graduate          916
High School       450
Name: count, dtype: int64

In [26]:
df['Most_Used_Platform'].value_counts()

Most_Used_Platform
Instagram    1130
TikTok        917
Facebook      717
LinkedIn      520
YouTube       488
Twitter       461
Snapchat      418
WhatsApp      175
LINE           50
VKontakte      40
KakaoTalk      36
WeChat         36
Name: count, dtype: int64

In [27]:
df['Purpose_Of_Use'].value_counts()

Purpose_Of_Use
Entertainment    2549
Education        1088
Networking        791
News              560
Name: count, dtype: int64

In [22]:
df['Stress_Level'].value_counts()

Stress_Level
Very High    1612
High         1438
Medium       1295
Low           643
Name: count, dtype: int64

In [30]:
df.corr(numeric_only=True)

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
Age,1.000000,-0.070300,-0.074325,0.083427,0.012623,0.088279,0.100420
Avg_Daily_Usage_Hours,-0.070300,1.000000,0.960162,-0.878847,-0.625326,-0.808602,-0.816049
Daily_Unlocks,-0.074325,0.960162,1.000000,-0.853530,-0.601726,-0.781801,-0.790287
Study_Hours,0.083427,-0.878847,-0.853530,1.000000,0.561769,0.730438,0.752454
Physical_Activity_Hours,0.012623,-0.625326,-0.601726,0.561769,1.000000,0.507392,0.520617
Sleep_Hours_Per_Night,0.088279,-0.808602,-0.781801,0.730438,0.507392,1.000000,0.766225
Mental_Health_Score,0.100420,-0.816049,-0.790287,0.752454,0.520617,0.766225,1.000000

In [31]:
df.describe()

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,4988.000000,4988.000000,4988.000000,4988.000000,4988.000000,4988.000000,4988.000000
mean,20.822374,5.074539,171.347835,3.010706,1.754671,6.636949,6.233841
std,1.737116,1.652778,42.827688,1.637380,0.663322,1.221215,1.278005
min,18.000000,1.000000,62.000000,0.300000,-0.000000,3.600000,3.600000
25%,19.000000,3.800000,140.000000,1.500000,1.300000,5.600000,5.100000
50%,21.000000,5.000000,171.000000,2.800000,1.700000,6.600000,6.100000
75%,22.000000,6.300000,204.000000,4.200000,2.200000,7.500000,7.100000
max,24.000000,8.800000,273.000000,8.300000,4.100000,9.900000,9.400000

In [29]:
X = df.drop('Mental_Health_Score', axis=1)

In [28]:
y = df['Mental_Health_Score']

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [33]:
print(X_train.shape)
print(X_test.shape)

(3990, 12)
(998, 12)

In [35]:
X.select_dtypes(include='object').columns

/var/folders/n6/vcd5gx3x0mg3jqnhg9z2c0gr0000gn/T/ipykernel_19706/2418744409.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X.select_dtypes(include='object').columns

Index(['Gender', 'Country', 'Academic_Level', 'Most_Used_Platform',
       'Purpose_Of_Use', 'Stress_Level'],
      dtype='str')

In [36]:
X.dtypes

Age                          int64
Gender                         str
Country                        str
Academic_Level                 str
Most_Used_Platform             str
Purpose_Of_Use                 str
Avg_Daily_Usage_Hours      float64
Daily_Unlocks                int64
Study_Hours                float64
Physical_Activity_Hours    float64
Sleep_Hours_Per_Night      float64
Stress_Level                   str
dtype: object

In [37]:
categorical_features = [
    'Gender',
    'Country',
    'Academic_Level',
    'Most_Used_Platform',
    'Purpose_Of_Use',
    'Stress_Level'
]

numerical_features = [
    'Age',
    'Avg_Daily_Usage_Hours',
    'Daily_Unlocks',
    'Study_Hours',
    'Physical_Activity_Hours',
    'Sleep_Hours_Per_Night'
]

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            numerical_features
        ),
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            categorical_features
        )
    ]
)

In [40]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [41]:
print("Original X_train shape:", X_train.shape)
print("Processed X_train shape:", X_train_processed.shape)

print("Original X_test shape:", X_test.shape)
print("Processed X_test shape:", X_test_processed.shape)

Original X_train shape: (3990, 12)
Processed X_train shape: (3990, 135)
Original X_test shape: (998, 12)
Processed X_test shape: (998, 135)

In [42]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train_processed, y_train)

LinearRegression()

In [43]:
y_pred = model.predict(X_test_processed)

In [44]:
comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

print(comparison.head(10))

   Actual  Predicted
0     4.3   4.872612
1     5.0   5.065545
2     5.0   5.806299
3     6.0   6.387429
4     5.0   4.698234
5     6.4   5.715149
6     6.1   5.976360
7     8.0   7.212658
8     8.0   7.742980
9     6.3   6.538040

In [45]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

MAE: 0.48038465945206826

In [46]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)

print("MSE:", mse)

MSE: 0.37001352338747373

In [47]:
import numpy as np

rmse = np.sqrt(mse)

print("RMSE:", rmse)

RMSE: 0.6082873690842789

In [48]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print("R2 Score:", r2)

R2 Score: 0.7827581200818104

In [49]:
# Using Random Forest

In [50]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

rf_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train_processed, y_train)

rf_pred = rf_model.predict(X_test_processed)

rf_mae = mean_absolute_error(y_test, rf_pred)
rf_mse = mean_squared_error(y_test, rf_pred)
rf_rmse = np.sqrt(rf_mse)
rf_r2 = r2_score(y_test, rf_pred)

print("Random Forest Performance")
print("-------------------------")
print("MAE :", rf_mae)
print("MSE :", rf_mse)
print("RMSE:", rf_rmse)
print("R²  :", rf_r2)

Random Forest Performance
-------------------------
MAE : 0.2706704742818975
MSE : 0.14204300891560925
RMSE: 0.37688593621360994
R²  : 0.9166038851673286